// .vitepress/theme/components/Download.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { marked, type MarkedOptions } from 'marked' // 从marked v4+开始支持具名导出

/*
  由于VitePress并不会解析该组件的latestRelease.body内容，故单独引入marked库解析为HTML后返回至页面
*/

interface DeviceType {
  id: string
  name: string
  icon: string
  description: string
  patterns: string[]
}

interface DownloadSource {
  id: string
  name: string
  description: string
  speed: string
}

const latestRelease = ref<any>(null)
const isLoading = ref(false)
const parsedBody = ref('')
const selectedDeviceType = ref('all')
const selectedDownloadSource = ref('github')
const isDeviceDropdownOpen = ref(false)
const isSourceDropdownOpen = ref(false)

// 基础设备类型定义（会根据API返回的文件动态扩展）
const baseDeviceTypes: DeviceType[] = [
  { 
    id: 'all', 
    name: '全部文件', 
    icon: '📦', 
    description: '显示所有下载文件',
    patterns: ['*']
  },
  { 
    id: 'windows', 
    name: 'Windows', 
    icon: '🪟', 
    description: 'Windows 电脑',
    patterns: ['windows', 'win', '.exe', '.msi']
  },
  { 
    id: 'macos', 
    name: 'macOS', 
    icon: '🍎', 
    description: 'Mac 电脑',
    patterns: ['macos', 'mac', 'darwin', '.dmg']
  },
  { 
    id: 'linux', 
    name: 'Linux', 
    icon: '🐧', 
    description: 'Linux 系统',
    patterns: ['linux', '.appimage', '.deb', '.rpm', '.tar.gz']
  },
  { 
    id: 'ios', 
    name: 'iOS', 
    icon: '📱', 
    description: 'iPhone/iPad',
    patterns: ['ios', '.ipa']
  }
]

// 下载源定义
const downloadSources: DownloadSource[] = [
  { id: 'github', name: 'GitHub 官方', description: '官方发布渠道', speed: '海外较快' },
  { id: 'mirror', name: '国内镜像', description: '第三方加速', speed: '国内较快' }
]

// 动态设备类型（基于API返回的文件）
const dynamicDeviceTypes = computed(() => {
  if (!latestRelease.value?.assets) return baseDeviceTypes

  const assets = latestRelease.value.assets
  const detectedTypes = new Set<string>()
  const architectures = new Set<string>()
  
  // 分析文件名，提取设备类型和架构信息
  assets.forEach((asset: any) => {
    const fileName = asset.name.toLowerCase()
    
    // 检测Android架构（按优先级检测，避免误匹配）
    if (fileName.includes('arm64-v8a') || fileName.includes('arm64')) {
      architectures.add('arm64')
    } else if (fileName.includes('armeabi-v7a') || fileName.includes('armeabi')) {
      architectures.add('armeabi')
    } else if (fileName.includes('x86_64') || fileName.includes('x86-64')) {
      architectures.add('x86_64')
    } else if (fileName.includes('x86')) {
      architectures.add('x86')
    } else if (fileName.includes('universal')) {
      architectures.add('universal')
    }
    
    // 检测平台
    baseDeviceTypes.forEach(type => {
      if (type.id !== 'all' && type.patterns.some(pattern => 
        pattern === '*' || fileName.includes(pattern.toLowerCase())
      )) {
        detectedTypes.add(type.id)
      }
    })
  })

  // 构建动态设备类型列表
  const result = [baseDeviceTypes[0]] // 始终包含 "全部文件"
  
  // 添加检测到的基础平台类型
  baseDeviceTypes.slice(1).forEach(type => {
    if (detectedTypes.has(type.id)) {
      result.push(type)
    }
  })
  
  // 添加架构特定的类型（按常见程度排序）
  const archOrder = ['arm64', 'armeabi', 'x86_64', 'x86', 'universal']
  archOrder.forEach(arch => {
    if (architectures.has(arch)) {
      const archType: DeviceType = {
        id: arch,
        name: getArchDisplayName(arch),
        icon: getArchIcon(arch),
        description: getArchDescription(arch),
        patterns: getArchPatterns(arch)
      }
      result.push(archType)
    }
  })
  
  return result
})

// 获取架构匹配模式
function getArchPatterns(arch: string): string[] {
  switch (arch) {
    case 'arm64': return ['arm64-v8a', 'arm64']
    case 'armeabi': return ['armeabi-v7a', 'armeabi']
    case 'x86_64': return ['x86_64', 'x86-64']
    case 'x86': return ['x86.apk'] // 精确匹配，避免匹配到x86_64
    case 'universal': return ['universal']
    default: return [arch]
  }
}

// 获取架构显示名称
function getArchDisplayName(arch: string): string {
  switch (arch) {
    case 'arm64': return 'ARM64'
    case 'armeabi': return 'ARMv7'
    case 'x86_64': return 'x86-64'
    case 'x86': return 'x86'
    case 'universal': return '通用版本'
    default: return arch.toUpperCase()
  }
}

// 获取架构图标
function getArchIcon(arch: string): string {
  switch (arch) {
    case 'arm64': return '💪'
    case 'armeabi': return '🔧'
    case 'x86_64': return '⚡'
    case 'x86': return '🔩'
    case 'universal': return '🌐'
    default: return '📱'
  }
}

// 获取架构描述
function getArchDescription(arch: string): string {
  switch (arch) {
    case 'arm64': return '64位 ARM 架构（推荐）'
    case 'armeabi': return '32位 ARM 架构'
    case 'x86_64': return '64位 x86 架构'
    case 'x86': return '32位 x86 架构'
    case 'universal': return '通用架构版本'
    default: return '特定架构'
  }
}

// 自动检测用户设备类型和架构
function detectUserDeviceType(): string {
  const userAgent = navigator.userAgent.toLowerCase()
  
  // 检测Android设备架构
  if (/android/.test(userAgent)) {
    // 尝试检测具体架构
    if (/arm64|aarch64/.test(userAgent)) {
      return 'arm64'
    } else if (/armv7|armeabi/.test(userAgent)) {
      return 'armeabi'
    } else if (/x86_64|x64/.test(userAgent)) {
      return 'x86_64'
    } else if (/x86/.test(userAgent)) {
      return 'x86'
    }
    // 默认推荐ARM64（现代Android设备主流架构）
    return 'arm64'
  } else if (/iphone|ipad|ipod/.test(userAgent)) {
    return 'ios'
  } else if (/mac/.test(userAgent)) {
    return 'macos'
  } else if (/win/.test(userAgent)) {
    return 'windows'
  } else if (/linux/.test(userAgent)) {
    return 'linux'
  }
  
  return 'all' // 默认显示全部
}

// 获取最新版本
async function fetchLatestRelease() {
  isLoading.value = true
  try {
    const response = await fetch('https://gayhub.lemwood.cn/repos/ZalithLauncher/ZalithLauncher/releases/latest')
    if (!response.ok) {
      throw new Error('Network response was not ok')
    }
    const data = await response.json()
    latestRelease.value = data
    // 显式等待marked解析完成
    parsedBody.value = data.body ? await marked.parse(data.body) : ''
    
    // 数据加载完成后自动检测设备类型
    autoSelectDeviceType()
  } catch (error) {
    console.error('Error fetching latest release:', error)
  } finally {
    isLoading.value = false
  }
}

onMounted(() => {
  fetchLatestRelease()
})

// 在数据加载完成后自动检测设备类型
function autoSelectDeviceType() {
  if (dynamicDeviceTypes.value.length > 1) {
    const detectedType = detectUserDeviceType()
    const availableType = dynamicDeviceTypes.value.find(type => type.id === detectedType)
    if (availableType) {
      selectedDeviceType.value = detectedType
    }
  }
}

// 按规则拼接镜像加速链接
function generateMirrorUrl(assetName: string, tagName: string) {
  const version = tagName.replace('v', '').replace(/\./g, '')
  return `https://download.fishcpy.top/dl/zl/${version}/${assetName}`
}

// GitHub下载链接
function getOriginalGitHubUrl(asset: any) {
  return asset.browser_download_url
}

// 根据设备类型过滤资源
const filteredAssets = computed(() => {
  if (!latestRelease.value?.assets) return []
  
  const assets = latestRelease.value.assets
  
  // 如果选择"全部文件"，返回所有资源
  if (selectedDeviceType.value === 'all') {
    return assets
  }
  
  // 查找当前选择的设备类型
  const currentType = dynamicDeviceTypes.value.find(type => type.id === selectedDeviceType.value)
  if (!currentType) return assets
  
  // 根据模式过滤文件
  return assets.filter((asset: any) => {
    const fileName = asset.name.toLowerCase()
    return currentType.patterns.some(pattern => {
      if (pattern === '*') return true
      return fileName.includes(pattern.toLowerCase())
    })
  })
})

// 获取当前选择的设备类型信息
const currentDeviceType = computed(() => {
  return dynamicDeviceTypes.value.find(type => type.id === selectedDeviceType.value) || dynamicDeviceTypes.value[0]
})

// 获取当前选择的下载源信息
const currentDownloadSource = computed(() => {
  return downloadSources.find(source => source.id === selectedDownloadSource.value) || downloadSources[0]
})

// 获取下载链接
function getDownloadUrl(asset: any) {
  if (selectedDownloadSource.value === 'mirror') {
    return generateMirrorUrl(asset.name, latestRelease.value.tag_name)
  } else {
    return getOriginalGitHubUrl(asset)
  }
}

// 格式化文件大小
function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 Bytes'
  const k = 1024
  const sizes = ['Bytes', 'KB', 'MB', 'GB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}
</script>

<template>
  <div class="download-container">
    <div v-if="isLoading" class="loading">
      <div class="loading-spinner"></div>
      <p>正在获取最新版本信息...</p>
    </div>
    
    <div v-else-if="latestRelease" class="release-info">
      <!-- 版本信息头部 -->
      <div class="release-header">
        <h2>{{ latestRelease.name }}</h2>
        <div class="version-info">
          <span class="version-tag">{{ latestRelease.tag_name }}</span>
          <span class="release-date">{{ new Date(latestRelease.published_at).toLocaleDateString('zh-CN') }}</span>
        </div>
      </div>
      
      <!-- 智能下载选择器 -->
      <div class="download-selector">
        <div class="selector-header">
          <h3>🎯 智能下载</h3>
          <p>已自动检测您的设备类型，您也可以手动选择</p>
        </div>
        
        <div class="selector-controls">
          <!-- 设备类型选择器 -->
          <div class="dropdown-container">
            <label class="dropdown-label">设备类型</label>
            <div class="dropdown" :class="{ 'is-open': isDeviceDropdownOpen }">
              <button 
                class="dropdown-trigger" 
                @click="isDeviceDropdownOpen = !isDeviceDropdownOpen"
                @blur="() => setTimeout(() => isDeviceDropdownOpen = false, 200)"
              >
                <span class="dropdown-content">
                  <span class="device-icon">{{ currentDeviceType.icon }}</span>
                  <span class="device-info">
                    <span class="device-name">{{ currentDeviceType.name }}</span>
                    <span class="device-desc">{{ currentDeviceType.description }}</span>
                  </span>
                </span>
                <span class="dropdown-arrow">▼</span>
              </button>
              
              <div class="dropdown-menu">
                <button 
                  v-for="device in dynamicDeviceTypes" 
                  :key="device.id"
                  class="dropdown-item"
                  :class="{ 'is-selected': selectedDeviceType === device.id }"
                  @click="selectedDeviceType = device.id; isDeviceDropdownOpen = false"
                >
                  <span class="device-icon">{{ device.icon }}</span>
                  <span class="device-info">
                    <span class="device-name">{{ device.name }}</span>
                    <span class="device-desc">{{ device.description }}</span>
                  </span>
                  <span v-if="selectedDeviceType === device.id" class="check-icon">✓</span>
                </button>
              </div>
            </div>
          </div>
          
          <!-- 下载源选择器 -->
          <div class="dropdown-container">
            <label class="dropdown-label">下载源</label>
            <div class="dropdown" :class="{ 'is-open': isSourceDropdownOpen }">
              <button 
                class="dropdown-trigger" 
                @click="isSourceDropdownOpen = !isSourceDropdownOpen"
                @blur="() => setTimeout(() => isSourceDropdownOpen = false, 200)"
              >
                <span class="dropdown-content">
                  <span class="source-info">
                    <span class="source-name">{{ currentDownloadSource.name }}</span>
                    <span class="source-desc">{{ currentDownloadSource.description }} · {{ currentDownloadSource.speed }}</span>
                  </span>
                </span>
                <span class="dropdown-arrow">▼</span>
              </button>
              
              <div class="dropdown-menu">
                <button 
                  v-for="source in downloadSources" 
                  :key="source.id"
                  class="dropdown-item"
                  :class="{ 'is-selected': selectedDownloadSource === source.id }"
                  @click="selectedDownloadSource = source.id; isSourceDropdownOpen = false"
                >
                  <span class="source-info">
                    <span class="source-name">{{ source.name }}</span>
                    <span class="source-desc">{{ source.description }} · {{ source.speed }}</span>
                  </span>
                  <span v-if="selectedDownloadSource === source.id" class="check-icon">✓</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <!-- 下载文件列表 -->
      <div class="download-section">
        <h3>📦 下载文件</h3>
        
        <div v-if="filteredAssets && filteredAssets.length > 0" class="assets-list">
          <div v-for="asset in filteredAssets" :key="asset.id" class="asset-item">
            <div class="asset-info">
              <div class="asset-header">
                <h4 class="asset-name">{{ asset.name }}</h4>
                <span class="asset-size">{{ formatFileSize(asset.size) }}</span>
              </div>
              <div class="asset-meta">
                <span class="download-count">📊 {{ asset.download_count.toLocaleString() }} 次下载</span>
              </div>
            </div>
            
            <div class="download-action">
              <a :href="getDownloadUrl(asset)" 
                 class="download-btn primary-btn" 
                 target="_blank" 
                 rel="noopener noreferrer">
                <span class="btn-icon">⬇️</span>
                <span class="btn-text">立即下载</span>
              </a>
            </div>
          </div>
        </div>
        
        <div v-else class="no-assets">
          <div class="no-assets-content">
            <span class="no-assets-icon">📱</span>
            <h4>暂无适用于 {{ currentDeviceType.name }} 的下载文件</h4>
            <p>请尝试选择其他设备类型，或查看完整的发布说明</p>
          </div>
        </div>
      </div>
      
      <!-- 发布说明 -->
      <div class="release-notes-section">
        <h3>📝 发布说明</h3>
        <div class="release-notes" v-html="parsedBody"></div>
      </div>
    </div>
    
    <div v-else class="error">
      <div class="error-content">
        <span class="error-icon">⚠️</span>
        <h3>无法获取版本信息</h3>
        <p>请检查网络连接后重试</p>
        <button class="retry-btn" @click="fetchLatestRelease()">重新加载</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.download-container {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* 加载和错误状态 */
.loading, .error {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 60px 20px;
  text-align: center;
}

.loading-spinner {
  width: 40px;
  height: 40px;
  border: 3px solid #f3f4f6;
  border-top: 3px solid #3b82f6;
  border-radius: 50%;
  animation: spin 1s linear infinite;
  margin-bottom: 16px;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

.loading p, .error-content p {
  color: #6b7280;
  margin: 0;
}

.error-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 16px;
}

.error-icon, .no-assets-icon {
  font-size: 3rem;
}

.error-icon {
  color: #ef4444;
}

.no-assets-icon {
  opacity: 0.5;
}

.error-content h3, .no-assets-content h4 {
  margin: 0;
  color: #374151;
}

.error-content h3 {
  font-size: 1.25rem;
}

.no-assets-content h4 {
  font-size: 1.125rem;
}

.retry-btn {
  background: #3b82f6;
  color: white;
  border: none;
  padding: 10px 20px;
  border-radius: 8px;
  cursor: pointer;
  font-weight: 600;
  transition: background-color 0.2s ease;
}

.retry-btn:hover {
  background: #1d4ed8;
}

/* 版本信息头部 */
.release-header {
  text-align: center;
  margin-bottom: 32px;
  padding: 24px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-radius: 16px;
  color: white;
}

.release-header h2 {
  margin: 0 0 12px 0;
  font-size: 2rem;
  font-weight: 700;
}

.version-info {
  display: flex;
  justify-content: center;
  gap: 16px;
  flex-wrap: wrap;
}

.version-tag, .release-date {
  padding: 6px 12px;
  border-radius: 20px;
  font-size: 0.875rem;
}

.version-tag {
  background: rgba(255, 255, 255, 0.2);
  font-weight: 600;
}

.release-date {
  background: rgba(255, 255, 255, 0.1);
}

/* 智能下载选择器 */
.download-selector {
  background: #f8fafc;
  border-radius: 16px;
  padding: 24px;
  margin-bottom: 32px;
  border: 1px solid #e2e8f0;
}

.selector-header {
  text-align: center;
  margin-bottom: 24px;
}

.selector-header h3, .download-section h3, .release-notes-section h3 {
  margin: 0 0 20px 0;
  font-size: 1.5rem;
  color: #1e293b;
}

.selector-header h3 {
  margin-bottom: 8px;
}

.selector-header p, .no-assets-content p {
  margin: 0;
  color: #64748b;
  font-size: 0.875rem;
}

.selector-controls {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 20px;
}

/* 下拉菜单 */
.dropdown-container {
  position: relative;
}

.dropdown-label {
  display: block;
  margin-bottom: 8px;
  font-weight: 600;
  color: #374151;
  font-size: 0.875rem;
}

.dropdown {
  position: relative;
}

.dropdown-trigger {
  width: 100%;
  background: white;
  border: 2px solid #e5e7eb;
  border-radius: 12px;
  padding: 12px 16px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  cursor: pointer;
  transition: all 0.2s ease;
  font-size: 0.875rem;
}

.dropdown-trigger:hover, .dropdown.is-open .dropdown-trigger {
  border-color: #3b82f6;
}

.dropdown.is-open .dropdown-trigger {
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

.dropdown-content {
  display: flex;
  align-items: center;
  gap: 12px;
  flex: 1;
}

.device-icon {
  font-size: 1.25rem;
}

.device-info, .source-info {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  text-align: left;
}

.device-name, .source-name {
  font-weight: 600;
  color: #1f2937;
  line-height: 1.2;
}

.device-desc, .source-desc {
  font-size: 0.75rem;
  color: #6b7280;
  line-height: 1.2;
}

.dropdown-arrow {
  color: #9ca3af;
  transition: transform 0.2s ease;
  font-size: 0.75rem;
}

.dropdown.is-open .dropdown-arrow {
  transform: rotate(180deg);
}

.dropdown-menu {
  position: absolute;
  top: 100%;
  left: 0;
  right: 0;
  background: white;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);
  z-index: 50;
  max-height: 300px;
  overflow-y: auto;
  opacity: 0;
  transform: translateY(-10px);
  pointer-events: none;
  transition: all 0.2s ease;
}

.dropdown.is-open .dropdown-menu {
  opacity: 1;
  transform: translateY(0);
  pointer-events: auto;
}

.dropdown-item {
  width: 100%;
  padding: 12px 16px;
  display: flex;
  align-items: center;
  gap: 12px;
  background: none;
  border: none;
  cursor: pointer;
  transition: background-color 0.2s ease;
  font-size: 0.875rem;
}

.dropdown-item:hover {
  background-color: #f3f4f6;
}

.dropdown-item.is-selected {
  background-color: #eff6ff;
  color: #1d4ed8;
}

.check-icon {
  margin-left: auto;
  color: #10b981;
  font-weight: bold;
}

/* 下载文件列表 */
.download-section, .release-notes-section {
  margin-bottom: 32px;
}

.assets-list {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.asset-item {
  background: white;
  border: 1px solid #e2e8f0;
  border-radius: 12px;
  padding: 20px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  transition: all 0.2s ease;
}

.asset-item:hover {
  border-color: #3b82f6;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
}

.asset-info {
  flex: 1;
}

.asset-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 8px;
}

.asset-name {
  margin: 0;
  font-size: 1.125rem;
  font-weight: 600;
  color: #1f2937;
}

.asset-size {
  background: #f3f4f6;
  padding: 4px 8px;
  border-radius: 6px;
  font-size: 0.75rem;
  color: #6b7280;
  font-weight: 500;
}

.download-count {
  font-size: 0.875rem;
  color: #6b7280;
}

.download-action {
  margin-left: 20px;
}

.download-btn {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 12px 24px;
  background: linear-gradient(135deg, #3b82f6, #1d4ed8);
  color: white;
  text-decoration: none;
  border-radius: 10px;
  font-weight: 600;
  transition: all 0.2s ease;
  box-shadow: 0 4px 12px rgba(59, 130, 246, 0.3);
}

.download-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 6px 20px rgba(59, 130, 246, 0.4);
}

.btn-icon {
  font-size: 1.125rem;
}

/* 无文件状态 */
.no-assets {
  text-align: center;
  padding: 40px 20px;
  background: #f8fafc;
  border-radius: 12px;
  border: 2px dashed #cbd5e1;
}

.no-assets-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
}

/* 发布说明 */
.release-notes {
  background: #f8fafc;
  border-radius: 12px;
  padding: 24px;
  border-left: 4px solid #3b82f6;
  line-height: 1.6;
}

/* 响应式设计 */
@media (max-width: 640px) {
  .download-container {
    padding: 16px;
  }
  
  .release-header {
    padding: 20px;
  }
  
  .release-header h2 {
    font-size: 1.5rem;
  }
  
  .download-selector {
    padding: 20px;
  }
  
  .selector-controls {
    grid-template-columns: 1fr;
  }
  
  .asset-item {
    flex-direction: column;
    align-items: stretch;
    gap: 16px;
  }
  
  .asset-header {
    flex-direction: column;
    align-items: flex-start;
    gap: 8px;
  }
  
  .download-action {
    margin-left: 0;
  }
  
  .download-btn {
    width: 100%;
    justify-content: center;
  }
}
</style>

// official-website/src/components/Download.tsx
import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Download, Smartphone, Terminal, ShieldCheck, Zap, Globe, ChevronDown, Check, AlertTriangle, ExternalLink, Info, Cloud } from 'lucide-react';
import { useLatestRelease, type Asset, LEMWOOD_API_BASE } from '../hooks/useLatestRelease';
import { marked } from 'marked';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { useTranslation } from 'react-i18next';

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

const DownloadSection = () => {
  const { t, i18n } = useTranslation();
  const [activeProject, setActiveProject] = useState<'zl1' | 'zl2'>('zl2');
  const { 
    release, 
    isReleaseLoading,
    isNotesLoading,
    isMirrorsLoading,
    isSyncing,
    error, 
    isChinaIP, 
    apiFailed, 
    mirrorData, 
    dynamicDeviceTypes, 
    localizedBody,
    cloudDrive,
    downloadSources 
  } = useLatestRelease(activeProject, i18n.language);

  const [selectedDevice, setSelectedDevice] = useState('all');
  const [selectedSource, setSelectedSource] = useState('github');
  const [isDeviceOpen, setIsDeviceOpen] = useState(false);
  const [isSourceOpen, setIsSourceOpen] = useState(false);
  const [parsedBody, setParsedBody] = useState('');
  const [downloadingAssets, setDownloadingAssets] = useState<Set<string | number>>(new Set());

  const ReleaseSkeleton = () => (
    <div className="glass-card p-4 sm:p-8 animate-pulse relative overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-r from-transparent via-[var(--bg-alt)] to-transparent opacity-20 skeleton-shimmer" />
      <div className="flex flex-wrap items-center justify-between gap-4 mb-8 relative z-10">
        <div>
          <div className="h-8 bg-[var(--bg-alt)] rounded w-48 mb-2" />
          <div className="h-4 bg-[var(--bg-alt)] rounded w-32" />
        </div>
        <div className="h-8 bg-[var(--bg-alt)] rounded w-20" />
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8 relative z-10">
        <div className="h-12 bg-[var(--bg-alt)] rounded-xl" />
        <div className="h-12 bg-[var(--bg-alt)] rounded-xl" />
      </div>
      <div className="space-y-3 relative z-10">
        {[1, 2, 3].map(i => (
          <div key={i} className="h-20 bg-[var(--bg-alt)] rounded-2xl flex items-center px-4 gap-4">
             <div className="w-10 h-10 bg-[var(--bg)] rounded-xl" />
             <div className="flex-1">
               <div className="h-4 bg-[var(--bg)] rounded w-1/3 mb-2" />
               <div className="h-3 bg-[var(--bg)] rounded w-1/4" />
             </div>
          </div>
        ))}
      </div>
      <div className="mt-6 flex items-center justify-center gap-2 text-[var(--text-2)] text-sm font-medium">
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ repeat: Infinity, duration: 1, ease: "linear" }}
        >
          <Zap size={16} className="text-[var(--brand)]" />
        </motion.div>
        正在获取最新版本信息...
      </div>
    </div>
  );

  const NotesSkeleton = () => (
    <div className="glass-card p-8 h-full animate-pulse bg-[var(--bg)]/40 backdrop-blur-md relative overflow-hidden flex flex-col">
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[var(--bg-alt)] to-transparent opacity-20 skeleton-shimmer" />
      <div className="h-6 bg-[var(--bg-alt)] rounded w-1/2 mb-6 relative z-10" />
      <div className="space-y-4 relative z-10 flex-1">
        {[1, 2, 3, 4, 5].map(i => (
          <div key={i} className="space-y-2">
            <div className="h-4 bg-[var(--bg-alt)] rounded" style={{ width: `${80 - i * 10}%` }} />
            <div className="h-4 bg-[var(--bg-alt)] rounded w-full" />
          </div>
        ))}
      </div>
      <div className="mt-8 pt-4 border-t border-[var(--divider)]/20 flex items-center justify-center gap-2 text-[var(--text-2)] text-sm font-medium relative z-10">
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ repeat: Infinity, duration: 1, ease: "linear" }}
        >
          <Zap size={16} className="text-[var(--brand)]" />
        </motion.div>
        正在拉取更新日志...
      </div>
    </div>
  );

  useEffect(() => {
    if (isChinaIP) {
      setSelectedSource('lemwood');
    }
  }, [isChinaIP]);

  // Auto-detect device type
  useEffect(() => {
    if (!isReleaseLoading && dynamicDeviceTypes.length > 1) {
      const ua = navigator.userAgent.toLowerCase();
      let detectedId = 'all';

      if (ua.includes('android')) {
        // 优先识别具体架构
        if (ua.includes('aarch64') || ua.includes('arm64')) {
          if (dynamicDeviceTypes.some(d => d.id === 'arm64')) {
            detectedId = 'arm64';
          }
        } else if (ua.includes('armv7') || ua.includes('armeabi')) {
          if (dynamicDeviceTypes.some(d => d.id === 'armeabi')) {
            detectedId = 'armeabi';
          }
        }
        
        // 如果没识别出具体架构，或者识别出的架构在列表中不存在，再回退到通用版本
        if (detectedId === 'all') {
          if (dynamicDeviceTypes.some(d => d.id === 'android')) {
            detectedId = 'android';
          }
        }
      }
      
      if (detectedId !== 'all') {
        setSelectedDevice(detectedId);
      }
    }
  }, [isReleaseLoading, dynamicDeviceTypes]);

  useEffect(() => {
    const parseContent = async () => {
      const displayBody = localizedBody || release?.body || '';
      if (displayBody) {
        try {
          const html = await marked.parse(displayBody);
          setParsedBody(html);
        } catch (e) {
          console.error('Failed to parse markdown', e);
        }
      } else {
        setParsedBody('');
      }
    };
    parseContent();
  }, [release, localizedBody]);

  const currentDevice = dynamicDeviceTypes.find(d => d.id === selectedDevice) || dynamicDeviceTypes[0];
  const currentSource = downloadSources.find(s => s.id === selectedSource) || downloadSources[0];

  const lemwoodSiteBase = LEMWOOD_API_BASE.replace('/api/v2', '');

  const getDownloadUrl = (asset: Asset) => {
    const tagName = release?.tag_name || '';
    
    if (selectedSource === 'mirror') {
      const version = activeProject === 'zl1' ? tagName.replace('v', '').replace(/\./g, '') : tagName.replace('v', '');
      return `https://download.fishcpy.top/dl/${activeProject === 'zl1' ? 'zl' : 'zl2'}/${version}/${asset.name}`;
    }

    if (selectedSource === 'foxington' && Array.isArray(mirrorData.foxington)) {
      const fileName = asset.name.toLowerCase();
      let targetArch = 'all 架构';
      if (fileName.includes('arm64')) targetArch = 'arm64-v8a 架构';
      else if (fileName.includes('armeabi')) targetArch = 'armeabi-v7a 架构';
      
      const matched = mirrorData.foxington.find((f: any) => f.name === targetArch);
      return matched?.url || asset.browser_download_url;
    }

    if (selectedSource === 'haha' && mirrorData.haha?.files && Array.isArray(mirrorData.haha.files)) {
      const fileName = asset.name.toLowerCase();
      let targetArch = '';
      if (fileName.includes('arm64')) targetArch = 'arm64-v8a';
      else if (fileName.includes('armeabi')) targetArch = 'armeabi-v7a';
      
      const matched = mirrorData.haha.files.find((f: any) => f.arch === targetArch || (!targetArch && (!f.arch || f.arch === 'all')));
      return matched?.link || asset.browser_download_url;
    }

    if (selectedSource === 'lemwood' && Array.isArray(mirrorData.lemwood)) {
      const currentTagName = release?.tag_name || '';
      const normalizedTagName = currentTagName.replace(/^v/, '');
      
      let matchedRelease = mirrorData.lemwood.find((r: any) => r.tag_name === currentTagName || r.tag_name === normalizedTagName);
      if (matchedRelease?.assets && Array.isArray(matchedRelease.assets)) {
        const matchedAsset = matchedRelease.assets.find((a: any) => a.name === asset.name);
        if (matchedAsset) return matchedAsset.url;
      }
      
      // Fallback: search by name in all releases
      for (let i = mirrorData.lemwood.length - 1; i >= 0; i--) {
        if (Array.isArray(mirrorData.lemwood[i].assets)) {
          const asset_match = mirrorData.lemwood[i].assets.find((a: any) => a.name === asset.name);
          if (asset_match) return asset_match.url;
        }
      }
    }

    return asset.browser_download_url;
  };

  const handleDownload = async (asset: Asset) => {
    if (selectedSource !== 'lemwood') {
      window.open(getDownloadUrl(asset), '_blank', 'noopener,noreferrer');
      return;
    }

    setDownloadingAssets(prev => new Set(prev).add(asset.id));
    try {
      const launcher = activeProject === 'zl1' ? 'zl' : 'zl2';
      const version = release?.tag_name?.replace(/^v/, '') || '';
      const filePath = `${launcher}/${version}/${asset.name}`;

      const res = await fetch(`${LEMWOOD_API_BASE}/downloads/prepare`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          file_path: filePath,
          return_url: window.location.href,
          source: 'zl-website-download'
        })
      });

      if (!res.ok) {
        throw new Error(`Prepare failed: ${res.status}`);
      }

      const result = await res.json();
      const payload = result.data ?? result;
      const downloadUrl = payload.download_url;

      if (downloadUrl) {
        const fullUrl = downloadUrl.startsWith('http') ? downloadUrl : `${lemwoodSiteBase}${downloadUrl}`;
        window.open(fullUrl, '_blank', 'noopener,noreferrer');
      } else {
        throw new Error('No download_url in response');
      }
    } catch (e) {
      console.error('Lemwood prepare download failed, falling back to direct URL', e);
      window.open(getDownloadUrl(asset), '_blank', 'noopener,noreferrer');
    } finally {
      setDownloadingAssets(prev => {
        const next = new Set(prev);
        next.delete(asset.id);
        return next;
      });
    }
  };

  const filteredAssets = release?.assets.filter(asset => {
    if (selectedDevice === 'all') return true;
    const name = asset.name.toLowerCase();
    
    // 特殊处理通用版本 (android id)
    if (selectedDevice === 'android') {
      return name.endsWith('.apk') && 
             !name.includes('arm64') && !name.includes('armv8') && 
             !name.includes('armeabi') && !name.includes('armv7') && 
             !name.includes('x86');
    }

    return currentDevice.patterns.some(p => p === '*' || name.includes(p.toLowerCase()));
  }) || [];

  const formatSize = (bytes: number) => {
    if (bytes === 0) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  return (
    <section id="download" className="py-24 relative overflow-hidden bg-[var(--bg-alt)] transition-colors duration-300">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <motion.h2 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-3xl md:text-5xl font-bold mb-6 text-[var(--text-1)]"
          >
            {t('download.title')}
          </motion.h2>
          
          {/* Project Switcher */}
          <div className="inline-flex p-1 bg-[var(--bg)] rounded-xl border border-[var(--divider)]/20 mb-8">
            <button
              onClick={() => setActiveProject('zl2')}
              className={cn(
                "px-6 py-2 rounded-lg text-sm font-medium transition-all",
                activeProject === 'zl2' 
                  ? "bg-[var(--brand)] text-white shadow-md dark:text-[var(--bg)]" 
                  : "text-[var(--text-2)] hover:bg-[var(--bg-alt)]"
              )}
            >
              Zalith Launcher 2 ({t('download.recommend')})
            </button>
            <button
              onClick={() => setActiveProject('zl1')}
              className={cn(
                "px-6 py-2 rounded-lg text-sm font-medium transition-all",
                activeProject === 'zl1' 
                  ? "bg-[var(--brand)] text-white shadow-md dark:text-[var(--bg)]" 
                  : "text-[var(--text-2)] hover:bg-[var(--bg-alt)]"
              )}
            >
              Zalith Launcher 1 ({t('download.legacy')})
            </button>
          </div>
        </div>

        {isReleaseLoading && isNotesLoading ? (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            <div className="lg:col-span-2 space-y-6 relative z-10">
              <ReleaseSkeleton />
            </div>
            <div className="lg:col-span-1 relative z-0">
              <NotesSkeleton />
            </div>
          </div>
        ) : error && !release ? (
          <div className="max-w-md mx-auto glass-card border-red-500/20 text-center p-12 bg-[var(--bg)]">
            <AlertTriangle className="w-12 h-12 text-red-500 mx-auto mb-4" />
            <h3 className="text-xl font-bold mb-2 text-[var(--text-1)]">{t('common.error')}</h3>
            <p className="text-[var(--text-2)] mb-6">{error}</p>
            <button onClick={() => window.location.reload()} className="btn-primary">{t('common.retry')}</button>
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Left: Release Info & Selector */}
            <div className="lg:col-span-2 space-y-6 relative z-10">
              {isReleaseLoading ? (
                <ReleaseSkeleton />
              ) : (
                <>
                  {apiFailed && (
                    <div className="p-4 bg-yellow-500/10 border border-yellow-500/20 rounded-xl flex items-start gap-3 text-yellow-700 dark:text-yellow-500 text-sm">
                      <AlertTriangle className="w-5 h-5 flex-shrink-0" />
                      <div>
                        <p className="font-bold">{t('download.apiFailed')}</p>
                        <p>{t('download.apiFailedDesc')}</p>
                      </div>
                    </div>
                  )}

                  <div className="glass-card p-4 sm:p-8">
                    <div className="flex flex-wrap items-center justify-between gap-4 mb-8">
                      <div>
                        <div className="flex items-center gap-3">
                          <h3 className="text-2xl font-bold text-[var(--brand)]">{release?.name}</h3>
                          {isSyncing && (
                            <span className="flex items-center gap-1 px-2 py-0.5 bg-[var(--brand)]/10 text-[var(--brand)] rounded text-xs">
                              <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1, ease: "linear" }}>
                                <Zap size={12} />
                              </motion.div>
                              更新中...
                            </span>
                          )}
                        </div>
                        <p className="text-[var(--text-2)] text-sm mt-1">
                          {t('download.publishedAt')} {release ? new Date(release.published_at).toLocaleDateString() : '-'}
                        </p>
                      </div>
                      <span className="px-3 py-1 bg-[var(--brand)]/10 text-[var(--brand)] rounded-full text-sm font-bold border border-[var(--brand)]/20">
                        {release?.tag_name}
                      </span>
                    </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
                  {/* Device Dropdown */}
                  <div className="relative">
                    <label className="block text-xs font-bold text-[var(--text-2)] mb-2 uppercase tracking-wider">{t('download.deviceType')}</label>
                    <button 
                      onClick={() => setIsDeviceOpen(!isDeviceOpen)}
                      className="w-full flex items-center justify-between px-4 py-3 bg-[var(--bg)] border border-[var(--divider)]/20 rounded-xl hover:border-[var(--brand)]/50 transition-all text-[var(--text-1)]"
                    >
                      <span className="flex items-center gap-3">
                        <Smartphone size={18} className="text-[var(--brand)]" />
                        <span className="text-sm font-medium">{currentDevice.name}</span>
                      </span>
                      <ChevronDown size={16} className={cn("transition-transform", isDeviceOpen && "rotate-180")} />
                    </button>
                    <AnimatePresence>
                      {isDeviceOpen && (
                        <>
                          <div className="fixed inset-0 z-10" onClick={() => setIsDeviceOpen(false)} />
                          <motion.div 
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: 10 }}
                            className="absolute top-full left-0 w-full mt-2 bg-[var(--bg)] border border-[var(--divider)]/20 rounded-xl shadow-2xl z-20 overflow-hidden"
                          >
                            {dynamicDeviceTypes.map(d => (
                              <button
                                key={d.id}
                                onClick={() => { setSelectedDevice(d.id); setIsDeviceOpen(false); }}
                                className="w-full flex items-center justify-between px-4 py-3 hover:bg-[var(--bg-alt)] text-left transition-colors text-[var(--text-1)]"
                              >
                                <div className="flex flex-col">
                                  <span className="text-sm font-bold">{d.name}</span>
                                  <span className="text-xs text-[var(--text-2)]">{d.description}</span>
                                </div>
                                {selectedDevice === d.id && <Check size={16} className="text-[var(--brand)]" />}
                              </button>
                            ))}
                          </motion.div>
                        </>
                      )}
                    </AnimatePresence>
                  </div>

                  {/* Source Dropdown */}
                  <div className="relative">
                    <label className="block text-xs font-bold text-[var(--text-2)] mb-2 uppercase tracking-wider flex items-center justify-between">
                      {t('download.source')}
                      {isMirrorsLoading && (
                        <span className="flex items-center gap-1 text-[var(--brand)] text-[10px] normal-case">
                          <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1, ease: "linear" }}>
                            <Zap size={10} />
                          </motion.div>
                          测速中...
                        </span>
                      )}
                    </label>
                    <button 
                      onClick={() => setIsSourceOpen(!isSourceOpen)}
                      disabled={isMirrorsLoading}
                      className={cn(
                        "w-full flex items-center justify-between px-4 py-3 bg-[var(--bg)] border border-[var(--divider)]/20 rounded-xl transition-all text-[var(--text-1)]",
                        isMirrorsLoading ? "opacity-70 cursor-not-allowed" : "hover:border-[var(--brand)]/50"
                      )}
                    >
                      <span className="flex items-center gap-3">
                        <Globe size={18} className="text-[var(--brand)]" />
                        <span className="text-sm font-medium">{currentSource.name}</span>
                      </span>
                      <ChevronDown size={16} className={cn("transition-transform", isSourceOpen && "rotate-180")} />
                    </button>
                    <AnimatePresence>
                      {isSourceOpen && (
                        <>
                          <div className="fixed inset-0 z-10" onClick={() => setIsSourceOpen(false)} />
                          <motion.div 
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: 10 }}
                            className="absolute top-full left-0 w-full mt-2 bg-[var(--bg)] border border-[var(--divider)]/20 rounded-xl shadow-2xl z-20 overflow-hidden"
                          >
                            {downloadSources.map(s => (
                              <button
                                key={s.id}
                                onClick={() => { setSelectedSource(s.id); setIsSourceOpen(false); }}
                                className="w-full px-4 py-3 hover:bg-[var(--bg-alt)] text-left transition-colors flex items-center justify-between text-[var(--text-1)]"
                              >
                                <div className="flex flex-col">
                                  <div className="flex items-center gap-2">
                                    <span className="text-sm font-bold">{s.name}</span>
                                    <span className="px-1.5 py-0.5 bg-green-500/10 text-green-600 dark:text-green-400 text-[10px] rounded uppercase">{s.speed}</span>
                                  </div>
                                  <span className="text-xs text-[var(--text-2)]">{s.description}</span>
                                </div>
                                {selectedSource === s.id && <Check size={16} className="text-[var(--brand)]" />}
                              </button>
                            ))}
                          </motion.div>
                        </>
                      )}
                    </AnimatePresence>
                  </div>
                </div>

                {/* Cloud Drive Links */}
                {cloudDrive && (
                  <div className="mb-6 p-4 bg-gradient-to-r from-blue-500/10 to-purple-500/10 border border-blue-500/20 rounded-2xl">
                    <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
                      <div className="flex items-center gap-3 flex-shrink-0">
                        <div className="w-10 h-10 bg-blue-500/20 text-blue-500 rounded-xl flex items-center justify-center flex-shrink-0">
                          <Cloud size={20} />
                        </div>
                        <div>
                          <p className="text-sm font-bold text-[var(--text-1)]">{t('download.cloudDrive')}</p>
                          <p className="text-xs text-[var(--text-2)]">{t('download.cloudDriveDesc')}</p>
                        </div>
                      </div>
                      <div className="flex flex-wrap gap-2 w-full sm:w-auto">
                        {(cloudDrive.links?.length ? cloudDrive.links : [{ name: t('download.cloudDriveBtn'), link: cloudDrive.link }]).map((drive: { name: string; link: string }, i: number) => (
                          <a
                            key={i}
                            href={drive.link}
                            target="_blank"
                            rel="noreferrer"
                            className="inline-flex items-center gap-2 px-3 py-2 sm:px-4 sm:py-2 bg-blue-500 hover:bg-blue-600 text-white rounded-xl text-xs sm:text-sm font-medium transition-colors whitespace-nowrap"
                          >
                            {drive.name} <ExternalLink size={14} />
                          </a>
                        ))}
                      </div>
                    </div>
                  </div>
                )}

                {/* Assets List */}
                <div className="space-y-3">
                  <h4 className="text-sm font-bold text-[var(--text-2)] mb-4 flex items-center gap-2">
                    <Download size={16} /> {t('download.assetsTitle')}
                  </h4>
                  {filteredAssets.length > 0 ? filteredAssets.map(asset => (
                    <motion.div 
                      key={asset.id}
                      layout
                      className="flex flex-col sm:flex-row items-start sm:items-center justify-between p-4 bg-[var(--bg-alt)] border border-[var(--divider)]/20 rounded-2xl hover:border-[var(--brand)]/30 transition-all gap-4"
                    >
                      <div className="flex items-start gap-4 flex-1 w-full">
                        <div className="w-10 h-10 bg-[var(--brand)]/10 text-[var(--brand)] rounded-xl flex items-center justify-center flex-shrink-0 mt-1 sm:mt-0 overflow-hidden">
                          {activeProject === 'zl2' ? (
                            <img src="/zl_icon.webp" alt="ZL2" className="w-6 h-6 object-contain" />
                          ) : (
                            <Terminal size={20} />
                          )}
                        </div>
                        <div className="min-w-0 flex-1">
                          <p className="text-sm font-bold text-[var(--text-1)] break-all sm:break-normal line-clamp-2 sm:line-clamp-1">{asset.name}</p>
                          <div className="flex flex-wrap items-center gap-x-3 gap-y-1 mt-1">
                            <span className="text-[10px] text-[var(--text-2)] font-medium uppercase whitespace-nowrap">{formatSize(asset.size)}</span>
                            <span className="w-1 h-1 bg-[var(--divider)]/50 rounded-full hidden sm:block" />
                            <span className="text-[10px] text-[var(--text-2)] font-medium uppercase whitespace-nowrap">{asset.download_count.toLocaleString()} {t('download.downloads')}</span>
                          </div>
                        </div>
                      </div>
                      <button
                        type="button"
                        onClick={() => handleDownload(asset)}
                        disabled={downloadingAssets.has(asset.id)}
                        className="btn-primary py-2 px-6 text-sm flex items-center gap-2 whitespace-nowrap w-full sm:w-auto justify-center disabled:opacity-70 disabled:cursor-not-allowed"
                      >
                        {downloadingAssets.has(asset.id) ? (
                          <>
                            <motion.div
                              animate={{ rotate: 360 }}
                              transition={{ repeat: Infinity, duration: 1, ease: "linear" }}
                            >
                              <Zap size={14} />
                            </motion.div>
                            {t('common.preparing') || '准备中'}
                          </>
                        ) : (
                          <>
                            {t('common.download')} <ExternalLink size={14} />
                          </>
                        )}
                      </button>
                    </motion.div>
                  )) : (
                    <div className="text-center py-12 bg-[var(--bg-alt)] rounded-2xl border border-dashed border-[var(--divider)]/50">
                      <Info className="w-8 h-8 text-[var(--text-2)] mx-auto mb-2 opacity-20" />
                      <p className="text-sm text-[var(--text-2)]">{t('download.noAssets')}</p>
                    </div>
                  )}
                </div>
              </div>
            </>
            )}
            </div>

            {/* Right: Release Notes */}
            <div className="lg:col-span-1 relative z-0">
              {isNotesLoading ? (
                <NotesSkeleton />
              ) : (
                <div className="glass-card p-8 h-full bg-[var(--bg)]/40 backdrop-blur-md">
                  <h4 className="text-lg font-bold mb-6 flex items-center gap-2 text-[var(--text-1)]">
                    <Info size={20} className="text-[var(--brand)]" /> {t('download.releaseNotes')}
                  </h4>
                  <div 
                    className="prose-custom text-sm overflow-y-auto max-h-[600px]"
                    dangerouslySetInnerHTML={{ __html: parsedBody }}
                  />
                  {!parsedBody && (
                    <p className="text-sm text-[var(--text-2)] italic">{t('download.noNotes')}</p>
                  )}
                </div>
              )}
            </div>
          </div>
        )}

        {/* Footer info */}
        <div className="mt-16 text-center">
          <div className="flex flex-wrap justify-center gap-8">
            <div className="flex items-center gap-2 text-[var(--text-2)] text-sm">
              <ShieldCheck size={16} className="text-green-500" />
              <span>{t('download.officialRelease')}</span>
            </div>
            <div className="flex items-center gap-2 text-[var(--text-2)] text-sm">
              <Zap size={16} className="text-yellow-500" />
              <span>{t('download.multiSource')}</span>
            </div>
            <div className="flex items-center gap-2 text-[var(--text-2)] text-sm">
              <Globe size={16} className="text-blue-500" />
              <span>{t('download.communityPowered')}</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DownloadSection;
